version: '3.8'

services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: data_base
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  server:
    build:
      context: ./server
      args:
         DATABASE_URL: postgres://user:password@db:5432/data_base
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/data_base
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - app-network

  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /client/node_modules
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://server:3001/api
    networks:
      - app-network


volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
